version: '3'
services:
    redis:
        image: 'redis:5.0.12-alpine'
        volumes:
            - 'koala_redis:/data'
        restart: unless-stopped
    koala:
        image: 'clivern/koala:release-1.0.6'
        ports:
            - "8080:8080"
        depends_on:
            - redis
        environment:
            KOALA_PORT: "8080"
            KOALA_REDIS_HOST: "redis"
            KOALA_REDIS_PORT: "6379"
            KOALA_REDIS_PASSWORD:
        restart: unless-stopped

volumes:
    koala_redis: null
